//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS_35.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASS_35.Resources.HomeText", typeof(HomeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept more information ?.
        /// </summary>
        public static string Accept_Add {
            get {
                return ResourceManager.GetString("Accept_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string Account_Information {
            get {
                return ResourceManager.GetString("Account_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account to be notified.
        /// </summary>
        public static string Account_to_be_notified {
            get {
                return ResourceManager.GetString("Account_to_be_notified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        public static string Account_type {
            get {
                return ResourceManager.GetString("Account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active And Send.
        /// </summary>
        public static string ActiveAndSend {
            get {
                return ResourceManager.GetString("ActiveAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Activity.
        /// </summary>
        public static string ActivityName {
            get {
                return ResourceManager.GetString("ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Activity.
        /// </summary>
        public static string ActivityType {
            get {
                return ResourceManager.GetString("ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new document theme.
        /// </summary>
        public static string Add_new_document_theme {
            get {
                return ResourceManager.GetString("Add_new_document_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new images theme.
        /// </summary>
        public static string Add_new_images_theme {
            get {
                return ResourceManager.GetString("Add_new_images_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new post.
        /// </summary>
        public static string Add_new_post {
            get {
                return ResourceManager.GetString("Add_new_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new video theme.
        /// </summary>
        public static string Add_new_video_theme {
            get {
                return ResourceManager.GetString("Add_new_video_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new place.
        /// </summary>
        public static string Add_Place {
            get {
                return ResourceManager.GetString("Add_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new speaker.
        /// </summary>
        public static string AddNew_Speaker {
            get {
                return ResourceManager.GetString("AddNew_Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Meeting.
        /// </summary>
        public static string AddNewMeeting {
            get {
                return ResourceManager.GetString("AddNewMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency information.
        /// </summary>
        public static string agency_information {
            get {
                return ResourceManager.GetString("agency_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All delegates.
        /// </summary>
        public static string All_delegates {
            get {
                return ResourceManager.GetString("All_delegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reporters.
        /// </summary>
        public static string All_reporters {
            get {
                return ResourceManager.GetString("All_reporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointment.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by.
        /// </summary>
        public static string Approved_by {
            get {
                return ResourceManager.GetString("Approved_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attached files.
        /// </summary>
        public static string Attached_files {
            get {
                return ResourceManager.GetString("Attached_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        public static string Authorities {
            get {
                return ResourceManager.GetString("Authorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar article (only accept png images, jpeg, gif ...).
        /// </summary>
        public static string Avatar_article {
            get {
                return ResourceManager.GetString("Avatar_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar posts.
        /// </summary>
        public static string Avatar_posts {
            get {
                return ResourceManager.GetString("Avatar_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing time.
        /// </summary>
        public static string Browsing_time {
            get {
                return ResourceManager.GetString("Browsing_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ButtonActiveAccount {
            get {
                return ResourceManager.GetString("ButtonActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive Account.
        /// </summary>
        public static string ButtonDeactiveAccount {
            get {
                return ResourceManager.GetString("ButtonDeactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string ButtonLockAccount {
            get {
                return ResourceManager.GetString("ButtonLockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Password.
        /// </summary>
        public static string Changes_Password {
            get {
                return ResourceManager.GetString("Changes_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the right choice.
        /// </summary>
        public static string Choose_the_right_choice {
            get {
                return ResourceManager.GetString("Choose_the_right_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string Company_Address {
            get {
                return ResourceManager.GetString("Company_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Detail.
        /// </summary>
        public static string Company_Detail {
            get {
                return ResourceManager.GetString("Company_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Email.
        /// </summary>
        public static string Company_Email {
            get {
                return ResourceManager.GetString("Company_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phone.
        /// </summary>
        public static string Company_Phone {
            get {
                return ResourceManager.GetString("Company_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this file ?.
        /// </summary>
        public static string Confirm_del_file {
            get {
                return ResourceManager.GetString("Confirm_del_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this place?.
        /// </summary>
        public static string Confirm_Dell_Location {
            get {
                return ResourceManager.GetString("Confirm_Dell_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirm_New_Pass {
            get {
                return ResourceManager.GetString("Confirm_New_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data, can not create report.
        /// </summary>
        public static string Confirm_nodata_no_reporter {
            get {
                return ResourceManager.GetString("Confirm_nodata_no_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMATION.
        /// </summary>
        public static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this account ?.
        /// </summary>
        public static string ConfirmDeleteAccount {
            get {
                return ResourceManager.GetString("ConfirmDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creators.
        /// </summary>
        public static string Creators {
            get {
                return ResourceManager.GetString("Creators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string Date_created {
            get {
                return ResourceManager.GetString("Date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Date_of_Birth {
            get {
                return ResourceManager.GetString("Date_of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string Date_Range {
            get {
                return ResourceManager.GetString("Date_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Date_start {
            get {
                return ResourceManager.GetString("Date_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string Deactive {
            get {
                return ResourceManager.GetString("Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate.
        /// </summary>
        public static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this information?.
        /// </summary>
        public static string Delete_infor {
            get {
                return ResourceManager.GetString("Delete_infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this post?.
        /// </summary>
        public static string Delete_Post {
            get {
                return ResourceManager.GetString("Delete_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this topic?.
        /// </summary>
        public static string Delete_Toppic {
            get {
                return ResourceManager.GetString("Delete_Toppic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter of recommendation.
        /// </summary>
        public static string Documentary {
            get {
                return ResourceManager.GetString("Documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in the topic.
        /// </summary>
        public static string Documents_in_the_topic {
            get {
                return ResourceManager.GetString("Documents_in_the_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account ?.
        /// </summary>
        public static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string Edit_article {
            get {
                return ResourceManager.GetString("Edit_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit document theme.
        /// </summary>
        public static string Edit_document_theme {
            get {
                return ResourceManager.GetString("Edit_document_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit video theme.
        /// </summary>
        public static string Edit_video_theme {
            get {
                return ResourceManager.GetString("Edit_video_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing photo themes.
        /// </summary>
        public static string Editing_photo_themes {
            get {
                return ResourceManager.GetString("Editing_photo_themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Introduction Conference.
        /// </summary>
        public static string EditIntroductionConference {
            get {
                return ResourceManager.GetString("EditIntroductionConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Meeting.
        /// </summary>
        public static string EditMeeting {
            get {
                return ResourceManager.GetString("EditMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial board.
        /// </summary>
        public static string Editorial_board {
            get {
                return ResourceManager.GetString("Editorial_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Place.
        /// </summary>
        public static string EditPlace {
            get {
                return ResourceManager.GetString("EditPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Speaker.
        /// </summary>
        public static string EditSpeaker {
            get {
                return ResourceManager.GetString("EditSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Account.
        /// </summary>
        public static string Email_Account {
            get {
                return ResourceManager.GetString("Email_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed video youtube.
        /// </summary>
        public static string Embed_video_youtube {
            get {
                return ResourceManager.GetString("Embed_video_youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string Expiration_Date {
            get {
                return ResourceManager.GetString("Expiration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded files.
        /// </summary>
        public static string File_upload {
            get {
                return ResourceManager.GetString("File_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin ASSA-35 design by QTW-HN.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string General_Information {
            get {
                return ResourceManager.GetString("General_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report.
        /// </summary>
        public static string Generate_report {
            get {
                return ResourceManager.GetString("Generate_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUESTSPEAKER.
        /// </summary>
        public static string GUESTSPEAKER {
            get {
                return ResourceManager.GetString("GUESTSPEAKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling.
        /// </summary>
        public static string Handling {
            get {
                return ResourceManager.GetString("Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required height = 392px.
        /// </summary>
        public static string HeightInval {
            get {
                return ResourceManager.GetString("HeightInval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min height 690 px.
        /// </summary>
        public static string HeightVenue {
            get {
                return ResourceManager.GetString("HeightVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card / Passport.
        /// </summary>
        public static string ID_Card_Passport {
            get {
                return ResourceManager.GetString("ID_Card_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Card Passport.
        /// </summary>
        public static string ID_Card_Passport_Image {
            get {
                return ResourceManager.GetString("ID_Card_Passport_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infor Meeting.
        /// </summary>
        public static string InforMeeting {
            get {
                return ResourceManager.GetString("InforMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce.
        /// </summary>
        public static string Introduce {
            get {
                return ResourceManager.GetString("Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations to the conference.
        /// </summary>
        public static string invitations_to_the_conference {
            get {
                return ResourceManager.GetString("invitations_to_the_conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEYNOTESPEAKER.
        /// </summary>
        public static string KEYNOTESPEAKER {
            get {
                return ResourceManager.GetString("KEYNOTESPEAKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Assa 35 Administration System.
        /// </summary>
        public static string lb_index {
            get {
                return ResourceManager.GetString("lb_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 File Chose.
        /// </summary>
        public static string Leng_File_Chose {
            get {
                return ResourceManager.GetString("Leng_File_Chose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link video (uploaded video link on website).
        /// </summary>
        public static string Link_video_upload {
            get {
                return ResourceManager.GetString("Link_video_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email and instructions will be sent to you!.
        /// </summary>
        public static string Mail_Recover {
            get {
                return ResourceManager.GetString("Mail_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main event.
        /// </summary>
        public static string MainE {
            get {
                return ResourceManager.GetString("MainE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage admin.
        /// </summary>
        public static string Manage_admin {
            get {
                return ResourceManager.GetString("Manage_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage delegates.
        /// </summary>
        public static string Manage_delegates {
            get {
                return ResourceManager.GetString("Manage_delegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage notifications.
        /// </summary>
        public static string Manage_notifications {
            get {
                return ResourceManager.GetString("Manage_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage reporter.
        /// </summary>
        public static string Manage_Reporter {
            get {
                return ResourceManager.GetString("Manage_Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage team members.
        /// </summary>
        public static string Manage_team_members {
            get {
                return ResourceManager.GetString("Manage_team_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the venue.
        /// </summary>
        public static string Manage_the_venue {
            get {
                return ResourceManager.GetString("Manage_the_venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Activity.
        /// </summary>
        public static string ManageActivity {
            get {
                return ResourceManager.GetString("ManageActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage contact information.
        /// </summary>
        public static string Manager_contact_infor {
            get {
                return ResourceManager.GetString("Manager_contact_infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Event.
        /// </summary>
        public static string ManagerEvent {
            get {
                return ResourceManager.GetString("ManagerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Management.
        /// </summary>
        public static string Meeting_Management {
            get {
                return ResourceManager.GetString("Meeting_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Name.
        /// </summary>
        public static string MeetingName {
            get {
                return ResourceManager.GetString("MeetingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy xác minh.
        /// </summary>
        public static string MemberLock {
            get {
                return ResourceManager.GetString("MemberLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min height : 350px.
        /// </summary>
        public static string Minheight {
            get {
                return ResourceManager.GetString("Minheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min width : 1140px.
        /// </summary>
        public static string Minwidth {
            get {
                return ResourceManager.GetString("Minwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contact.
        /// </summary>
        public static string Name_Contact {
            get {
                return ResourceManager.GetString("Name_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name delegates.
        /// </summary>
        public static string Name_delegates {
            get {
                return ResourceManager.GetString("Name_delegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the meeting.
        /// </summary>
        public static string Name_meeting {
            get {
                return ResourceManager.GetString("Name_meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of organization/ delegate.
        /// </summary>
        public static string Name_of_organization_delegate {
            get {
                return ResourceManager.GetString("Name_of_organization_delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of organization/ reporter.
        /// </summary>
        public static string Name_of_organization_reporter {
            get {
                return ResourceManager.GetString("Name_of_organization_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the place.
        /// </summary>
        public static string Name_the_place {
            get {
                return ResourceManager.GetString("Name_the_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Event name.
        /// </summary>
        public static string NameEvent {
            get {
                return ResourceManager.GetString("NameEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        public static string New_messages {
            get {
                return ResourceManager.GetString("New_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string No_data {
            get {
                return ResourceManager.GetString("No_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data in the table.
        /// </summary>
        public static string No_data_table {
            get {
                return ResourceManager.GetString("No_data_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no lines.
        /// </summary>
        public static string No_line {
            get {
                return ResourceManager.GetString("No_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Name.
        /// </summary>
        public static string Notice_Name {
            get {
                return ResourceManager.GetString("Notice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Notifi_Active {
            get {
                return ResourceManager.GetString("Notifi_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string Notifi_Deactive {
            get {
                return ResourceManager.GetString("Notifi_Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Notifi_Pending {
            get {
                return ResourceManager.GetString("Notifi_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employee Cards.
        /// </summary>
        public static string Number_of_employee_Cards {
            get {
                return ResourceManager.GetString("Number_of_employee_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string Order_number {
            get {
                return ResourceManager.GetString("Order_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANELIST.
        /// </summary>
        public static string PANELIST {
            get {
                return ResourceManager.GetString("PANELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Registration.
        /// </summary>
        public static string Parking_Registration {
            get {
                return ResourceManager.GetString("Parking_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass word.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Detail.
        /// </summary>
        public static string Person_Detail {
            get {
                return ResourceManager.GetString("Person_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo employee Card.
        /// </summary>
        public static string Photo_employee_Card {
            get {
                return ResourceManager.GetString("Photo_employee_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of ID Card / Passport Backside.
        /// </summary>
        public static string Photo_of_ID_Card_Passport_Backside {
            get {
                return ResourceManager.GetString("Photo_of_ID_Card_Passport_Backside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of ID Card / Passport Front.
        /// </summary>
        public static string Photo_of_ID_Card_Passport_Front {
            get {
                return ResourceManager.GetString("Photo_of_ID_Card_Passport_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures in the topic.
        /// </summary>
        public static string Pictures_in_the_topic {
            get {
                return ResourceManager.GetString("Pictures_in_the_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of issue.
        /// </summary>
        public static string Place_of_issue {
            get {
                return ResourceManager.GetString("Place_of_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post website.
        /// </summary>
        public static string PostWebsite {
            get {
                return ResourceManager.GetString("PostWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation skills.
        /// </summary>
        public static string Presentationskills {
            get {
                return ResourceManager.GetString("Presentationskills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive this email notification.
        /// </summary>
        public static string Receive_this_email_notification {
            get {
                return ResourceManager.GetString("Receive_this_email_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string Recover_Password {
            get {
                return ResourceManager.GetString("Recover_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register from.
        /// </summary>
        public static string Register_from {
            get {
                return ResourceManager.GetString("Register_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveOnSite.
        /// </summary>
        public static string RemoveOnSite {
            get {
                return ResourceManager.GetString("RemoveOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter.
        /// </summary>
        public static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter name.
        /// </summary>
        public static string Reporter_name {
            get {
                return ResourceManager.GetString("Reporter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post news via website.
        /// </summary>
        public static string Reporting_Status {
            get {
                return ResourceManager.GetString("Reporting_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Registration.
        /// </summary>
        public static string Room_Registration {
            get {
                return ResourceManager.GetString("Room_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft.
        /// </summary>
        public static string Save_Draft {
            get {
                return ResourceManager.GetString("Save_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and post website.
        /// </summary>
        public static string SaveAndPost {
            get {
                return ResourceManager.GetString("SaveAndPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and post admin.
        /// </summary>
        public static string SaveAndPostAdmin {
            get {
                return ResourceManager.GetString("SaveAndPostAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and send.
        /// </summary>
        public static string SaveandSend {
            get {
                return ResourceManager.GetString("SaveandSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by content ....
        /// </summary>
        public static string Search_Content {
            get {
                return ResourceManager.GetString("Search_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretariat.
        /// </summary>
        public static string Secretariat {
            get {
                return ResourceManager.GetString("Secretariat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string Select_file {
            get {
                return ResourceManager.GetString("Select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all notifications.
        /// </summary>
        public static string Sell_all {
            get {
                return ResourceManager.GetString("Sell_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ line.
        /// </summary>
        public static string Show_menu_line {
            get {
                return ResourceManager.GetString("Show_menu_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status file.
        /// </summary>
        public static string Status_File {
            get {
                return ResourceManager.GetString("Status_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to forum postings.
        /// </summary>
        public static string Subscribe_to_forum_postings {
            get {
                return ResourceManager.GetString("Subscribe_to_forum_postings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary file.
        /// </summary>
        public static string Summaryfile {
            get {
                return ResourceManager.GetString("Summaryfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string TA {
            get {
                return ResourceManager.GetString("TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string Team_Members {
            get {
                return ResourceManager.GetString("Team_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time end.
        /// </summary>
        public static string Time_end {
            get {
                return ResourceManager.GetString("Time_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time register.
        /// </summary>
        public static string Time_register {
            get {
                return ResourceManager.GetString("Time_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time start.
        /// </summary>
        public static string Time_start {
            get {
                return ResourceManager.GetString("Time_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to send.
        /// </summary>
        public static string Time_to_send {
            get {
                return ResourceManager.GetString("Time_to_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time End.
        /// </summary>
        public static string TimeE {
            get {
                return ResourceManager.GetString("TimeE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Start.
        /// </summary>
        public static string TimeS {
            get {
                return ResourceManager.GetString("TimeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string To_date {
            get {
                return ResourceManager.GetString("To_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name.
        /// </summary>
        public static string Topic_name {
            get {
                return ResourceManager.GetString("Topic_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic status.
        /// </summary>
        public static string Topic_status {
            get {
                return ResourceManager.GetString("Topic_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total _TOTAL_ line.
        /// </summary>
        public static string Total_line {
            get {
                return ResourceManager.GetString("Total_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Account.
        /// </summary>
        public static string Type_of_Account {
            get {
                return ResourceManager.GetString("Type_of_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name.
        /// </summary>
        public static string Unit_name {
            get {
                return ResourceManager.GetString("Unit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update the information ?.
        /// </summary>
        public static string Update_infor {
            get {
                return ResourceManager.GetString("Update_infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document file (only accept .pdf, .ppt,.pptx file).
        /// </summary>
        public static string Upload_document_file {
            get {
                return ResourceManager.GetString("Upload_document_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload images (only accept png, jpeg, gif).
        /// </summary>
        public static string Upload_images_file {
            get {
                return ResourceManager.GetString("Upload_images_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload invitations file.
        /// </summary>
        public static string Upload_invitations_file {
            get {
                return ResourceManager.GetString("Upload_invitations_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video in the topic.
        /// </summary>
        public static string Video_in_the_topic {
            get {
                return ResourceManager.GetString("Video_in_the_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese Website.
        /// </summary>
        public static string Vietnamese_Website {
            get {
                return ResourceManager.GetString("Vietnamese_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation of the terms of the organizers.
        /// </summary>
        public static string Violation_of_the_terms_of_the_organizers {
            get {
                return ResourceManager.GetString("Violation_of_the_terms_of_the_organizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website English.
        /// </summary>
        public static string Website_English {
            get {
                return ResourceManager.GetString("Website_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required width = 1140px.
        /// </summary>
        public static string WidthInval {
            get {
                return ResourceManager.GetString("WidthInval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min width 1140 px.
        /// </summary>
        public static string WidthVenue {
            get {
                return ResourceManager.GetString("WidthVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string You_have {
            get {
                return ResourceManager.GetString("You_have", resourceCulture);
            }
        }
    }
}
