//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_activity_detail
    {
        public int id { get; set; }
        public Nullable<int> idActivity { get; set; }
        public string actDetail { get; set; }
        public string actValue { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual m_activity m_activity { get; set; }
    }
}
