//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_activity()
        {
            this.m_activity_detail = new HashSet<m_activity_detail>();
        }
    
        public int id { get; set; }
        public string actName { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> idActType { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> idNguoitao { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> idNguoiduyet { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public Nullable<int> phienban { get; set; }
        public string lydotuchoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_activity_detail> m_activity_detail { get; set; }
        public virtual m_activity_type m_activity_type { get; set; }
    }
}
