//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_baivietgioithieu
    {
        public int id { get; set; }
        public string tenmenu { get; set; }
        public string noidung { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string url { get; set; }
    }
}
