//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_chucnangtaikhoan
    {
        public int id { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> iddanhmuc { get; set; }
        public Nullable<int> idquyen { get; set; }
    
        public virtual m_danhmuc m_danhmuc { get; set; }
        public virtual m_quyen m_quyen { get; set; }
    }
}
