//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_chitietthongbao
    {
        public int id { get; set; }
        public int idthongbao { get; set; }
        public int idtaikhoan { get; set; }
        public System.DateTime ngaytao { get; set; }
        public int trangthai { get; set; }
        public bool daxem { get; set; }
    
        public virtual m_taikhoan m_taikhoan { get; set; }
        public virtual m_thongbao m_thongbao { get; set; }
    }
}
