//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_danhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_danhmuc()
        {
            this.m_chucnangtaikhoan = new HashSet<m_chucnangtaikhoan>();
        }
    
        public int id { get; set; }
        public string tendanhmuc { get; set; }
        public string url { get; set; }
        public string physical { get; set; }
        public Nullable<int> ismenu { get; set; }
        public Nullable<int> stt { get; set; }
        public string icon { get; set; }
        public Nullable<int> idcha { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string tendanhmucEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_chucnangtaikhoan> m_chucnangtaikhoan { get; set; }
    }
}
