//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_lienhe
    {
        public int id { get; set; }
        public string tendonvi { get; set; }
        public Nullable<System.DateTime> thoigiantao { get; set; }
        public Nullable<int> idnguoitao { get; set; }
        public string diachi { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> idnguoiduyet { get; set; }
        public Nullable<System.DateTime> thoigianduyet { get; set; }
        public Nullable<int> phienban { get; set; }
        public string noidung { get; set; }
    }
}
