//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_mediadetails
    {
        public int id { get; set; }
        public string duongdanfile { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string kieufile { get; set; }
        public string caption { get; set; }
        public Nullable<int> idmedia { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public string tenfile { get; set; }
        public Nullable<int> idtaikhoan { get; set; }
        public string mimetype { get; set; }
        public Nullable<int> size { get; set; }
    
        public virtual m_media m_media { get; set; }
    }
}
