//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_media()
        {
            this.m_mediadetails = new HashSet<m_mediadetails>();
        }
    
        public int id { get; set; }
        public string tenchude { get; set; }
        public Nullable<System.DateTime> thoigiantao { get; set; }
        public Nullable<int> idnguoitao { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string ghichu { get; set; }
        public string gioithieu { get; set; }
        public Nullable<int> idnguoipheduyet { get; set; }
        public Nullable<System.DateTime> thoigianpheduyet { get; set; }
        public string url { get; set; }
        public Nullable<int> phienban { get; set; }
        public string theloai { get; set; }
        public string tennguoitao { get; set; }
        public string tennguoipheduyet { get; set; }
        public string lydo { get; set; }
        public Nullable<int> luotxem { get; set; }
    
        public virtual m_taikhoan m_taikhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_mediadetails> m_mediadetails { get; set; }
    }
}
