//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_quyentaikhoan
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> idtaikhoan { get; set; }
        public Nullable<int> idquyen { get; set; }
    
        public virtual m_quyen m_quyen { get; set; }
        public virtual m_taikhoan m_taikhoan { get; set; }
        public virtual m_trangthai m_trangthai { get; set; }
    }
}
