//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_regisActivity
    {
        public int id { get; set; }
        public Nullable<int> idRegis { get; set; }
        public Nullable<int> idActivity { get; set; }
        public Nullable<int> value0 { get; set; }
        public Nullable<int> idActDetail { get; set; }
        public string value2 { get; set; }
    
        public virtual m_registration_info m_registration_info { get; set; }
    }
}
