//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_room_show_option1
    {
        public int id { get; set; }
        public Nullable<int> idRoomShow { get; set; }
        public Nullable<int> idRoomOption1 { get; set; }
    
        public virtual m_room_show m_room_show { get; set; }
    }
}
