//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_room_show
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_room_show()
        {
            this.m_room_show_option1 = new HashSet<m_room_show_option1>();
        }
    
        public int id { get; set; }
        public Nullable<int> idHotel { get; set; }
        public Nullable<int> idRoomType { get; set; }
        public string priceEn { get; set; }
        public string priceVi { get; set; }
        public Nullable<bool> show { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_room_show_option1> m_room_show_option1 { get; set; }
    }
}
