//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_room_order
    {
        public int id { get; set; }
        public Nullable<int> idHotel { get; set; }
        public Nullable<int> idRoomType { get; set; }
        public Nullable<int> idRoomOption1 { get; set; }
        public Nullable<int> idRoomOption2 { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public string otherreq { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
