//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_slidetrangchu
    {
        public int id { get; set; }
        public string tenanh { get; set; }
        public string trichdan { get; set; }
        public Nullable<int> stt { get; set; }
        public string duongdan { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> idnguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> phienban { get; set; }
        public Nullable<int> idnguoisua { get; set; }
        public string hinhanh { get; set; }
        public string site { get; set; }
    }
}
