//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_speaker
    {
        public int id { get; set; }
        public string hoten { get; set; }
        public string chucvu { get; set; }
        public string avatar { get; set; }
        public string file_abstract { get; set; }
        public string presentation { get; set; }
        public string noidung { get; set; }
        public string type { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> stt { get; set; }
    }
}
