//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_sukienhop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_sukienhop()
        {
            this.m_chitietsukienhop = new HashSet<m_chitietsukienhop>();
        }
    
        public int id { get; set; }
        public System.DateTime thoigiantao { get; set; }
        public int idnguoitao { get; set; }
        public int trangthai { get; set; }
        public Nullable<int> idnguoiduyet { get; set; }
        public Nullable<System.DateTime> thoigianduyet { get; set; }
        public string tencuochop { get; set; }
        public int phienban { get; set; }
        public string lydotuchoi { get; set; }
        public string diadiem { get; set; }
        public Nullable<System.DateTime> ngayhop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_chitietsukienhop> m_chitietsukienhop { get; set; }
    }
}
