//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_taikhoan()
        {
            this.m_chitietthongbao = new HashSet<m_chitietthongbao>();
            this.m_cuochop = new HashSet<m_cuochop>();
            this.m_media = new HashSet<m_media>();
            this.m_quyentaikhoan = new HashSet<m_quyentaikhoan>();
            this.m_thongtincanhan = new HashSet<m_thongtincanhan>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<int> idloaitaikhoan { get; set; }
        public string avatar { get; set; }
        public string giaymoi { get; set; }
        public string lydo { get; set; }
        public Nullable<int> idcoquan { get; set; }
        public Nullable<bool> isConfirmEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_chitietthongbao> m_chitietthongbao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_cuochop> m_cuochop { get; set; }
        public virtual m_loaitaikhoan m_loaitaikhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_media> m_media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_quyentaikhoan> m_quyentaikhoan { get; set; }
        public virtual m_thongtincoquan m_thongtincoquan { get; set; }
        public virtual m_trangthai m_trangthai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_thongtincanhan> m_thongtincanhan { get; set; }
    }
}
