//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_thongbao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_thongbao()
        {
            this.m_chitietguimedia = new HashSet<m_chitietguimedia>();
            this.m_chitietthongbao = new HashSet<m_chitietthongbao>();
            this.m_filethongbao = new HashSet<m_filethongbao>();
        }
    
        public int id { get; set; }
        public string tenthongbao { get; set; }
        public Nullable<System.DateTime> thoigiantao { get; set; }
        public Nullable<int> idnguoitao { get; set; }
        public string noidung { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> phienban { get; set; }
        public Nullable<int> idnguoiduyet { get; set; }
        public Nullable<System.DateTime> thoigianduyet { get; set; }
        public string lido { get; set; }
        public Nullable<int> target { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_chitietguimedia> m_chitietguimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_chitietthongbao> m_chitietthongbao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_filethongbao> m_filethongbao { get; set; }
    }
}
