//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_thongtincoquan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_thongtincoquan()
        {
            this.m_taikhoan = new HashSet<m_taikhoan>();
        }
    
        public int id { get; set; }
        public string tencoquan { get; set; }
        public string diachicoquan { get; set; }
        public string sofax { get; set; }
        public string emailcoquan { get; set; }
        public string filecongvan { get; set; }
        public string sodienthoai { get; set; }
        public Nullable<int> trangthaiduatin { get; set; }
        public int quocgia { get; set; }
        public Nullable<int> phienban { get; set; }
    
        public virtual m_quocgia m_quocgia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<m_taikhoan> m_taikhoan { get; set; }
    }
}
