//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASS_35Entities : DbContext
    {
        public ASS_35Entities()
            : base("name=ASS_35Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_activity> m_activity { get; set; }
        public virtual DbSet<m_activity_detail> m_activity_detail { get; set; }
        public virtual DbSet<m_activity_type> m_activity_type { get; set; }
        public virtual DbSet<m_baiviet> m_baiviet { get; set; }
        public virtual DbSet<m_baivietgioithieu> m_baivietgioithieu { get; set; }
        public virtual DbSet<m_chitietguimedia> m_chitietguimedia { get; set; }
        public virtual DbSet<m_chitietsukienhop> m_chitietsukienhop { get; set; }
        public virtual DbSet<m_chitietthongbao> m_chitietthongbao { get; set; }
        public virtual DbSet<m_chucnangtaikhoan> m_chucnangtaikhoan { get; set; }
        public virtual DbSet<m_cuochop> m_cuochop { get; set; }
        public virtual DbSet<m_danhmuc> m_danhmuc { get; set; }
        public virtual DbSet<m_diadiemtochuc> m_diadiemtochuc { get; set; }
        public virtual DbSet<m_dvtruyenthong> m_dvtruyenthong { get; set; }
        public virtual DbSet<m_filethongbao> m_filethongbao { get; set; }
        public virtual DbSet<m_hotel> m_hotel { get; set; }
        public virtual DbSet<m_lienhe> m_lienhe { get; set; }
        public virtual DbSet<m_loaitaikhoan> m_loaitaikhoan { get; set; }
        public virtual DbSet<m_media> m_media { get; set; }
        public virtual DbSet<m_mediadetails> m_mediadetails { get; set; }
        public virtual DbSet<m_menuclient> m_menuclient { get; set; }
        public virtual DbSet<m_quocgia> m_quocgia { get; set; }
        public virtual DbSet<m_quyen> m_quyen { get; set; }
        public virtual DbSet<m_quyentaikhoan> m_quyentaikhoan { get; set; }
        public virtual DbSet<m_regisActivity> m_regisActivity { get; set; }
        public virtual DbSet<m_registration_info> m_registration_info { get; set; }
        public virtual DbSet<m_room_option1> m_room_option1 { get; set; }
        public virtual DbSet<m_room_option2> m_room_option2 { get; set; }
        public virtual DbSet<m_room_order> m_room_order { get; set; }
        public virtual DbSet<m_room_show> m_room_show { get; set; }
        public virtual DbSet<m_room_show_option1> m_room_show_option1 { get; set; }
        public virtual DbSet<m_room_show_option2> m_room_show_option2 { get; set; }
        public virtual DbSet<m_room_type> m_room_type { get; set; }
        public virtual DbSet<m_slidetrangchu> m_slidetrangchu { get; set; }
        public virtual DbSet<m_speaker> m_speaker { get; set; }
        public virtual DbSet<m_sukienhop> m_sukienhop { get; set; }
        public virtual DbSet<m_taikhoan> m_taikhoan { get; set; }
        public virtual DbSet<m_thongbao> m_thongbao { get; set; }
        public virtual DbSet<m_thongtincanhan> m_thongtincanhan { get; set; }
        public virtual DbSet<m_thongtincoquan> m_thongtincoquan { get; set; }
        public virtual DbSet<m_trangthai> m_trangthai { get; set; }
        public virtual DbSet<meal_preference> meal_preference { get; set; }
    
        public virtual ObjectResult<ActivityInfomation_Result> ActivityInfomation(Nullable<int> roleId, Nullable<int> myId, Nullable<int> statusId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var myIdParameter = myId.HasValue ?
                new ObjectParameter("myId", myId) :
                new ObjectParameter("myId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActivityInfomation_Result>("ActivityInfomation", roleIdParameter, myIdParameter, statusIdParameter);
        }
    
        public virtual ObjectResult<ContactInfomation_Result> ContactInfomation(Nullable<int> myId, Nullable<int> statusId)
        {
            var myIdParameter = myId.HasValue ?
                new ObjectParameter("myId", myId) :
                new ObjectParameter("myId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ContactInfomation_Result>("ContactInfomation", myIdParameter, statusIdParameter);
        }
    
        public virtual ObjectResult<CreateReportPersonal_Result> CreateReportPersonal(string kEY, Nullable<int> lOAITK, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var lOAITKParameter = lOAITK.HasValue ?
                new ObjectParameter("LOAITK", lOAITK) :
                new ObjectParameter("LOAITK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateReportPersonal_Result>("CreateReportPersonal", kEYParameter, lOAITKParameter, totalCount);
        }
    
        public virtual ObjectResult<GetListActivity_Result> GetListActivity(Nullable<int> typeAct)
        {
            var typeActParameter = typeAct.HasValue ?
                new ObjectParameter("typeAct", typeAct) :
                new ObjectParameter("typeAct", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListActivity_Result>("GetListActivity", typeActParameter);
        }
    
        public virtual ObjectResult<ListNotificationPerson_Result> ListNotificationPerson(Nullable<int> myId)
        {
            var myIdParameter = myId.HasValue ?
                new ObjectParameter("myId", myId) :
                new ObjectParameter("myId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListNotificationPerson_Result>("ListNotificationPerson", myIdParameter);
        }
    
        public virtual ObjectResult<LOAD_DETAIL_MEETING_Result> LOAD_DETAIL_MEETING(string kEY, Nullable<int> bSEARCH, Nullable<int> tRANGTHAI, Nullable<int> iD, Nullable<int> sESSION_ID, Nullable<int> sESSION_QUYEN, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var bSEARCHParameter = bSEARCH.HasValue ?
                new ObjectParameter("BSEARCH", bSEARCH) :
                new ObjectParameter("BSEARCH", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            var sESSION_QUYENParameter = sESSION_QUYEN.HasValue ?
                new ObjectParameter("SESSION_QUYEN", sESSION_QUYEN) :
                new ObjectParameter("SESSION_QUYEN", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DETAIL_MEETING_Result>("LOAD_DETAIL_MEETING", kEYParameter, bSEARCHParameter, tRANGTHAIParameter, iDParameter, sESSION_IDParameter, sESSION_QUYENParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<LOAD_DOCUMENT_POSTER_Result> LOAD_DOCUMENT_POSTER(string kEY, Nullable<int> bSEARCH, string tYPE, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var bSEARCHParameter = bSEARCH.HasValue ?
                new ObjectParameter("BSEARCH", bSEARCH) :
                new ObjectParameter("BSEARCH", typeof(int));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DOCUMENT_POSTER_Result>("LOAD_DOCUMENT_POSTER", kEYParameter, bSEARCHParameter, tYPEParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<LOADALL_MEDIA_Result> LOADALL_MEDIA(string kEY, Nullable<int> bSEARCH, Nullable<int> tRANGTHAI, string tYPE, Nullable<int> sESSION_ID, Nullable<int> sESSION_QUYEN, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var bSEARCHParameter = bSEARCH.HasValue ?
                new ObjectParameter("BSEARCH", bSEARCH) :
                new ObjectParameter("BSEARCH", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            var sESSION_QUYENParameter = sESSION_QUYEN.HasValue ?
                new ObjectParameter("SESSION_QUYEN", sESSION_QUYEN) :
                new ObjectParameter("SESSION_QUYEN", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADALL_MEDIA_Result>("LOADALL_MEDIA", kEYParameter, bSEARCHParameter, tRANGTHAIParameter, tYPEParameter, sESSION_IDParameter, sESSION_QUYENParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<LOADALL_MEETING_Result> LOADALL_MEETING(string kEY, Nullable<int> bSEARCH, Nullable<int> tRANGTHAI, string nGAYHOP, Nullable<int> sESSION_ID, Nullable<int> sESSION_QUYEN, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var bSEARCHParameter = bSEARCH.HasValue ?
                new ObjectParameter("BSEARCH", bSEARCH) :
                new ObjectParameter("BSEARCH", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var nGAYHOPParameter = nGAYHOP != null ?
                new ObjectParameter("NGAYHOP", nGAYHOP) :
                new ObjectParameter("NGAYHOP", typeof(string));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            var sESSION_QUYENParameter = sESSION_QUYEN.HasValue ?
                new ObjectParameter("SESSION_QUYEN", sESSION_QUYEN) :
                new ObjectParameter("SESSION_QUYEN", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADALL_MEETING_Result>("LOADALL_MEETING", kEYParameter, bSEARCHParameter, tRANGTHAIParameter, nGAYHOPParameter, sESSION_IDParameter, sESSION_QUYENParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<LOADALL_POST_Result> LOADALL_POST(string kEY, Nullable<int> bSEARCH, Nullable<int> tRANGTHAI, Nullable<int> sESSION_ID, Nullable<int> sESSION_QUYEN, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var bSEARCHParameter = bSEARCH.HasValue ?
                new ObjectParameter("BSEARCH", bSEARCH) :
                new ObjectParameter("BSEARCH", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            var sESSION_QUYENParameter = sESSION_QUYEN.HasValue ?
                new ObjectParameter("SESSION_QUYEN", sESSION_QUYEN) :
                new ObjectParameter("SESSION_QUYEN", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADALL_POST_Result>("LOADALL_POST", kEYParameter, bSEARCHParameter, tRANGTHAIParameter, sESSION_IDParameter, sESSION_QUYENParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<ManagerAccount_Result> ManagerAccount(Nullable<int> roleId, Nullable<int> statusId, string txtSearch, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            var txtSearchParameter = txtSearch != null ?
                new ObjectParameter("txtSearch", txtSearch) :
                new ObjectParameter("txtSearch", typeof(string));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ManagerAccount_Result>("ManagerAccount", roleIdParameter, statusIdParameter, txtSearchParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<ManagerStatistical_Result> ManagerStatistical(string kEY, Nullable<int> lOAITK, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var lOAITKParameter = lOAITK.HasValue ?
                new ObjectParameter("LOAITK", lOAITK) :
                new ObjectParameter("LOAITK", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ManagerStatistical_Result>("ManagerStatistical", kEYParameter, lOAITKParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<MeetingInfomation_Result> MeetingInfomation(Nullable<int> roleId, Nullable<int> myId, Nullable<int> statusId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var myIdParameter = myId.HasValue ?
                new ObjectParameter("myId", myId) :
                new ObjectParameter("myId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MeetingInfomation_Result>("MeetingInfomation", roleIdParameter, myIdParameter, statusIdParameter);
        }
    
        public virtual ObjectResult<NotificationManager_Result> NotificationManager(Nullable<int> roleId, Nullable<int> myId, Nullable<int> statusId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var myIdParameter = myId.HasValue ?
                new ObjectParameter("myId", myId) :
                new ObjectParameter("myId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificationManager_Result>("NotificationManager", roleIdParameter, myIdParameter, statusIdParameter);
        }
    
        public virtual ObjectResult<SlideInformation_Result> SlideInformation(Nullable<int> roleid, Nullable<int> site)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var siteParameter = site.HasValue ?
                new ObjectParameter("site", site) :
                new ObjectParameter("site", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SlideInformation_Result>("SlideInformation", roleidParameter, siteParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<Sp_GetActivityRegis_Result> Sp_GetActivityRegis(Nullable<int> idregis)
        {
            var idregisParameter = idregis.HasValue ?
                new ObjectParameter("idregis", idregis) :
                new ObjectParameter("idregis", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetActivityRegis_Result>("Sp_GetActivityRegis", idregisParameter);
        }
    
        public virtual ObjectResult<SP_GetListActById_Result> SP_GetListActById(Nullable<int> idregis)
        {
            var idregisParameter = idregis.HasValue ?
                new ObjectParameter("idregis", idregis) :
                new ObjectParameter("idregis", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetListActById_Result>("SP_GetListActById", idregisParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_LIBRARY_IMAGES_Result> SP_LIBRARY_IMAGES(Nullable<int> moidang, Nullable<int> xemnhieu, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var moidangParameter = moidang.HasValue ?
                new ObjectParameter("moidang", moidang) :
                new ObjectParameter("moidang", typeof(int));
    
            var xemnhieuParameter = xemnhieu.HasValue ?
                new ObjectParameter("xemnhieu", xemnhieu) :
                new ObjectParameter("xemnhieu", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LIBRARY_IMAGES_Result>("SP_LIBRARY_IMAGES", moidangParameter, xemnhieuParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<SP_LIBRARY_VIDEO_Result> SP_LIBRARY_VIDEO(Nullable<int> moidang, Nullable<int> xemnhieu, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var moidangParameter = moidang.HasValue ?
                new ObjectParameter("moidang", moidang) :
                new ObjectParameter("moidang", typeof(int));
    
            var xemnhieuParameter = xemnhieu.HasValue ?
                new ObjectParameter("xemnhieu", xemnhieu) :
                new ObjectParameter("xemnhieu", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LIBRARY_VIDEO_Result>("SP_LIBRARY_VIDEO", moidangParameter, xemnhieuParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<SP_LOADALL_NEWS_Result> SP_LOADALL_NEWS(Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOADALL_NEWS_Result>("SP_LOADALL_NEWS", currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<SP_LOADALL_SUKIEN_Result> SP_LOADALL_SUKIEN(Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOADALL_SUKIEN_Result>("SP_LOADALL_SUKIEN", currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<SP_LOADALL_TINTUC_Result> SP_LOADALL_TINTUC(Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOADALL_TINTUC_Result>("SP_LOADALL_TINTUC", currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<SP_MANAGER_MEETING_EVENT_Result> SP_MANAGER_MEETING_EVENT(string kEY, Nullable<int> bSEARCH, Nullable<int> tRANGTHAI, Nullable<int> sESSION_ID, Nullable<int> sESSION_QUYEN, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
        {
            var kEYParameter = kEY != null ?
                new ObjectParameter("KEY", kEY) :
                new ObjectParameter("KEY", typeof(string));
    
            var bSEARCHParameter = bSEARCH.HasValue ?
                new ObjectParameter("BSEARCH", bSEARCH) :
                new ObjectParameter("BSEARCH", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var sESSION_IDParameter = sESSION_ID.HasValue ?
                new ObjectParameter("SESSION_ID", sESSION_ID) :
                new ObjectParameter("SESSION_ID", typeof(int));
    
            var sESSION_QUYENParameter = sESSION_QUYEN.HasValue ?
                new ObjectParameter("SESSION_QUYEN", sESSION_QUYEN) :
                new ObjectParameter("SESSION_QUYEN", typeof(int));
    
            var currPageParameter = currPage.HasValue ?
                new ObjectParameter("currPage", currPage) :
                new ObjectParameter("currPage", typeof(int));
    
            var recodperpageParameter = recodperpage.HasValue ?
                new ObjectParameter("recodperpage", recodperpage) :
                new ObjectParameter("recodperpage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MANAGER_MEETING_EVENT_Result>("SP_MANAGER_MEETING_EVENT", kEYParameter, bSEARCHParameter, tRANGTHAIParameter, sESSION_IDParameter, sESSION_QUYENParameter, currPageParameter, recodperpageParameter, totalCount);
        }
    
        public virtual ObjectResult<SP_MEETING_Result> SP_MEETING(string nGAYHOP)
        {
            var nGAYHOPParameter = nGAYHOP != null ?
                new ObjectParameter("NGAYHOP", nGAYHOP) :
                new ObjectParameter("NGAYHOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MEETING_Result>("SP_MEETING", nGAYHOPParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<VenueInfomation_Result> VenueInfomation(Nullable<int> roleId, Nullable<int> myId, Nullable<int> statusId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var myIdParameter = myId.HasValue ?
                new ObjectParameter("myId", myId) :
                new ObjectParameter("myId", typeof(int));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VenueInfomation_Result>("VenueInfomation", roleIdParameter, myIdParameter, statusIdParameter);
        }
    }
}
